/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.quanlynhankhau;

import DAO.loadDAO;
import Entity.quanlytamtru;
import context.ShareData;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;

import java.util.Date;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class FORMQUANLYTAMTRU extends javax.swing.JFrame {

    /**
     * Creates new form QUANLYTAMTRU
     */
    public FORMQUANLYTAMTRU() {
        initComponents();
        processLoginSuccessful();
        ShareData.state=false;
        loadDAO ld = new loadDAO();
        List<quanlytamtru> list=ld.getALLquanlytamtru();
        DefaultTableModel model= (DefaultTableModel)tbquanlytamtru.getModel();// muốn dùng table thì pải có hàm này 
        for(quanlytamtru o : list){
            model.addRow(new Object[]{o.getMaTamTru(),o.getHoTen(),o.getNTNS(),o.getGioiTinh(),o.getNoiOTamTru(),o.getNgayDangKy(),o.getNgayChuyenDen(),o.getNgayRoiDi(),o.getMaSoNhanKhau()});
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbquanlytamtru = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMatamtru = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHovaten = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNoitamtru = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMasonhankhau = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        txtNTNS = new com.toedter.calendar.JDateChooser();
        txtNgaydangky = new com.toedter.calendar.JDateChooser();
        txtNgaychuyenden = new com.toedter.calendar.JDateChooser();
        txtNgayroidi = new com.toedter.calendar.JDateChooser();
        jComboBoxnamnu = new javax.swing.JComboBox<>();
        btnTIMKIEM = new javax.swing.JButton();
        txtotrongnhiunam = new javax.swing.JTextField();
        btnNhapmoi = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtotrongbaolau = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtGioitinh = new javax.swing.JTextField();
        btnThoat = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtobaonhiuthang = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jTextField8.setText("jTextField1");

        jLabel8.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        tbquanlytamtru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "maTamTru", "HoTen", "NTNS", "GioiTinh", "NoiOTamTru", "NgayDangKy", "NgayChuyenDen", "NgayRoiDi", "maSoNhanKhau"
            }
        ));
        tbquanlytamtru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbquanlytamtruMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbquanlytamtru);

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mã tạm trú:");

        txtMatamtru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatamtruActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Họ và tên:");

        txtHovaten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHovatenActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NTNS:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nơi tạm trú:");

        txtNoitamtru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoitamtruActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Giới tính:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ngày đăng ký:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ngày chuyển đến:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ngày rời đi:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mã số nhân khẩu:");

        txtMasonhankhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMasonhankhauActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(255, 255, 0));
        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(255, 255, 0));
        btnSua.setText("SỬA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 255, 0));
        btnXoa.setText("XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        txtNTNS.setDateFormatString("yyyy-MM-dd");

        txtNgaydangky.setDateFormatString("yyyy-MM-dd");

        txtNgaychuyenden.setDateFormatString("yyyy-MM-dd");
        txtNgaychuyenden.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtNgaychuyendenAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        txtNgayroidi.setDateFormatString("yyyy-MM-dd");

        jComboBoxnamnu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        jComboBoxnamnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxnamnuActionPerformed(evt);
            }
        });

        btnTIMKIEM.setText("TÌM");
        btnTIMKIEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTIMKIEMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMatamtru, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHovaten, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNTNS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtNoitamtru)
                    .addComponent(jComboBoxnamnu, 0, 133, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMasonhankhau, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNgayroidi, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNgaychuyenden, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(48, 48, 48))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(btnTIMKIEM, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNgaydangky, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtMatamtru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel7)
                        .addComponent(jComboBoxnamnu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNgaychuyenden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtHovaten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNoitamtru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel9))
                    .addComponent(txtNgayroidi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtMasonhankhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNTNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgaydangky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTIMKIEM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        txtotrongnhiunam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtotrongnhiunamActionPerformed(evt);
            }
        });

        btnNhapmoi.setText("NHẬP MỚI");
        btnNhapmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapmoiActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("QUẢN LÝ TẠM TRÚ");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Đã ở trong:");

        txtotrongbaolau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtotrongbaolauActionPerformed(evt);
            }
        });

        jLabel13.setText("ngày");

        txtGioitinh.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        txtGioitinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGioitinhActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(255, 255, 0));
        btnThoat.setText("THOÁT");
        btnThoat.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnThoatAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel14.setText("năm");

        txtobaonhiuthang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtobaonhiuthangActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("=");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("=");

        jLabel17.setText("tháng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtotrongbaolau, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(txtobaonhiuthang, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtotrongnhiunam, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnNhapmoi)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(182, 182, 182)))
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNhapmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtotrongnhiunam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtotrongbaolau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(txtobaonhiuthang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        ShareData.state=true;
//        trangmain tr = new  trangmain();
//        tr
      
//        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_btnThoatActionPerformed
    
    private void btnNhapmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapmoiActionPerformed
        // TODO add your handling code here:
        txtGioitinh.setText("");
        txtHovaten.setText("");
        txtMasonhankhau.setText("");
        txtMatamtru.setText("");
        txtNoitamtru.setText("");
        txtotrongbaolau.setText("");
        txtobaonhiuthang.setText("");
        txtotrongnhiunam.setText("");
        txtNTNS.setCalendar(null);
        txtNgaychuyenden.setCalendar(null);
        txtNgaydangky.setCalendar(null);
        txtNgayroidi.setCalendar(null);
        
        loadDAO ld1 =new loadDAO();
         List<quanlytamtru> list=ld1.getALLquanlytamtru();
        DefaultTableModel model= (DefaultTableModel)tbquanlytamtru.getModel();// muốn dùng table thì pải có hàm này 
        model.setRowCount(0);//clear thable
        for(quanlytamtru o : list){
            model.addRow(new Object[]{o.getMaTamTru(),o.getHoTen(),o.getNTNS(),o.getGioiTinh(),o.getNoiOTamTru(),o.getNgayDangKy(),o.getNgayChuyenDen(),o.getNgayRoiDi(),o.getMaSoNhanKhau()});
            
        }
        
    }//GEN-LAST:event_btnNhapmoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        StringBuilder sb =new StringBuilder();
        if(txtMatamtru.getText().equals("")){
            sb.append("Số sổ hộ khẩu không được để trống");
            txtMatamtru.setBackground(Color.yellow);
        }else{
             txtMatamtru.setBackground(Color.white);
        }
        if(sb.length()>0){
            JOptionPane.showMessageDialog(this, sb);// cái này là để in ra cái lỗi dòng 258 ở trên
            return;
        }
        
        try {
            SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");// muốn dùng dc date time thì pải có hai dòng này dòng 1
            String dateNTNS = sdf.format(txtNTNS.getDate());// dòng 2.
            String dateNgaychuyenden=sdf.format(txtNgaychuyenden.getDate());
            String dateNgaydangky =sdf.format(txtNgaydangky.getDate());
            String dateNgayroidi =sdf.format(txtNgayroidi.getDate());
            quanlytamtru qltt = new quanlytamtru();
//            qltt.setSoSHK(Integer.parseInt(txtSoSHK.getText()));
//            qlshk.setNgaycap(date);
//            qlshk.setNoithuongtru(txtNoithuongtru.getText());
//            qlshk.setTenchuho(txtTenchuho.getText());
            qltt.setMaTamTru(txtMatamtru.getText());
            qltt.setGioiTinh(txtGioitinh.getText());
            qltt.setHoTen(txtHovaten.getText());
            qltt.setMaSoNhanKhau(txtMasonhankhau.getText());
            qltt.setNoiOTamTru(txtNoitamtru.getText());
            qltt.setNTNS(dateNTNS);
            qltt.setNgayChuyenDen(dateNgaychuyenden);
            qltt.setNgayDangKy(dateNgaydangky);
            qltt.setNgayRoiDi(dateNgayroidi);
            
//            String matamtruString=txtMatamtru.getText();
//            String hotenString=txtGioitinh.getText();
//            String gioitinhString=txtGioitinh.getText();
//            String masonhankhauString=txtMasonhankhau.getText();
//            String noiotamtruString=txtNoitamtru.getText();
//            Date ngay =txtNTNS.getDate();
            
            loadDAO ld1 =new loadDAO();
            ld1.insert(qltt);
            
            List<quanlytamtru> list=ld1.getALLquanlytamtru();
        DefaultTableModel model= (DefaultTableModel)tbquanlytamtru.getModel();// muốn dùng table thì pải có hàm này 
        model.setRowCount(0);//clear thable
        for(quanlytamtru o : list){
            model.addRow(new Object[]{o.getMaTamTru(),o.getHoTen(),o.getNTNS(),o.getGioiTinh(),o.getNoiOTamTru(),o.getNgayDangKy(),o.getNgayChuyenDen(),o.getNgayRoiDi(),o.getMaSoNhanKhau()});
            
        }

            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR:" +e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void tbquanlytamtruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbquanlytamtruMouseClicked
        // TODO add your handling code here:
        int row = tbquanlytamtru.getSelectedRow();
//        o.getSoSHK(),o.getNoithuongtru(),o.getTenchuho(),o.getNgaycap
//        String SoSHK=tbquanlysohokhau.getValueAt(row, 0).toString();
//        String Noithuongtru=tbquanlysohokhau.getValueAt(row, 1).toString();
//        String Tenchuho=tbquanlysohokhau.getValueAt(row, 2).toString();
//      ĐÂY LÀ LẤY DỮ LEEIUJ TỪ TABLE BÊN FORM VÔ NÊN STRING HẾT.
        String matamtru=tbquanlytamtru.getValueAt(row, 0).toString();
        String hoten=tbquanlytamtru.getValueAt(row, 1).toString();
        String NTNS=tbquanlytamtru.getValueAt(row, 2).toString();
        String gioitinh=tbquanlytamtru.getValueAt(row, 3).toString();
        String noiotamtru=tbquanlytamtru.getValueAt(row, 4).toString();
        String ngaydangky=tbquanlytamtru.getValueAt(row, 5).toString();
        String ngaychuyenden=tbquanlytamtru.getValueAt(row, 6).toString();
        String ngayroidi=tbquanlytamtru.getValueAt(row, 7).toString();
        String masonhankhau=tbquanlytamtru.getValueAt(row, 8).toString();
        
//        txtSoSHK.setText(SoSHK);
//        txtNoithuongtru.setText(Noithuongtru);
//        txtTenchuho.setText(Tenchuho);
// KHÚC NÀY MỚI SET GIÁ TRỊ
            txtMatamtru.setText(matamtru);
            txtHovaten.setText(hoten);
            txtGioitinh.setText(gioitinh);
            txtMasonhankhau.setText(masonhankhau);
            txtNoitamtru.setText(noiotamtru);
            
//            String dateBeforeString = "2022-07-20";
//	String dateAfterString = "2023-06-25";

	LocalDate dateBefore = LocalDate.parse(ngaychuyenden);
	LocalDate dateAfter = LocalDate.parse(ngayroidi);
		
	long noOfDaysBetween = ChronoUnit.DAYS.between(dateBefore, dateAfter);
        long nam=0;
        long ngay=noOfDaysBetween;
        long ngay1=noOfDaysBetween;
        long thang=0;
        while(ngay>=365){
        
            nam= nam +1;
            ngay= ngay-365;
            
        
        }
        while(ngay1>=30){
        
            thang= thang +1;
            ngay1= ngay1-30;
            
        
        }
		
//	System.out.println(noOfDaysBetween);
        String timeer = String.valueOf(noOfDaysBetween);
        String timeerss = String.valueOf(nam);
        String timeersss = String.valueOf(thang);
        txtotrongbaolau.setText(timeer);
        txtotrongnhiunam.setText(timeerss);
        txtobaonhiuthang.setText(timeersss);
            
        
//        import java.text.SimpleDateFormat;  lên trên thêm 2 thư viện này vô thư viện 1
//import java.util.Date;  thư viện 2 

        Date date1;
        try {
            date1 = new SimpleDateFormat("yyyy-MM-dd").parse(NTNS);
//            txtNTNS.setDate(date1);set date thì date còn giờ là mình đế bên entity là string nên set string;
                txtNTNS.setDate(date1);
        } catch (ParseException ex) {
            Logger.getLogger(FORMQUANLYTAMTRU.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Date date2;
        try {
            date2 = new SimpleDateFormat("yyyy-MM-dd").parse(ngaydangky);
            txtNgaydangky.setDate(date2);
        } catch (ParseException ex) {
            Logger.getLogger(FORMQUANLYTAMTRU.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Date date3;
        try {
            date3 = new SimpleDateFormat("yyyy-MM-dd").parse(ngaychuyenden);
            txtNgaychuyenden.setDate(date3);
        } catch (ParseException ex) {
            Logger.getLogger(FORMQUANLYTAMTRU.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Date date4;
        try {
            date4 = new SimpleDateFormat("yyyy-MM-dd").parse(ngayroidi);
            txtNgayroidi.setDate(date4);
        } catch (ParseException ex) {
            Logger.getLogger(FORMQUANLYTAMTRU.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_tbquanlytamtruMouseClicked

    private void btnTIMKIEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTIMKIEMActionPerformed
        
//        if(txtTIMKIEM.getText().equals("")){
//            JOptionPane.showMessageDialog(this, "BẠN CHƯA NHẬP GÌ CẢ!!!");
//            return;
//        }
        txtMatamtruActionPerformed(evt);
        txtGioitinhActionPerformed(evt);
         //
        if(txtNgaychuyenden!=null){
        try {
            SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");// muốn dùng dc date time thì pải có hai dòng này dòng 1
            String dateNaychuyden = sdf.format(txtNgaychuyenden.getDate());// dòng 2.
            loadDAO ld = new loadDAO();
            List<quanlytamtru> quanlytamtrus=null;
            quanlytamtrus=ld.findByNgayChuyenDen(dateNaychuyden);
            
            if(quanlytamtrus!=null){
                DefaultTableModel model= (DefaultTableModel)tbquanlytamtru.getModel();// muốn dùng table thì pải có hàm này 
        model.setRowCount(0);//clear thable
            for(quanlytamtru o : quanlytamtrus){
            model.addRow(new Object[]{o.getMaTamTru(),o.getHoTen(),o.getNTNS(),o.getGioiTinh(),o.getNoiOTamTru(),o.getNgayDangKy(),o.getNgayChuyenDen(),o.getNgayRoiDi(),o.getMaSoNhanKhau()});
            
        }
            }
            
        } catch (Exception e) {

        }
        }
        //
        
        
        if(txtNgayroidi!=null){
         try {
            SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");// muốn dùng dc date time thì pải có hai dòng này dòng 1
            String dateNayroidi = sdf.format(txtNgayroidi.getDate());// dòng 2.
            loadDAO ld = new loadDAO();
            List<quanlytamtru> quanlytamtrus=null;
            quanlytamtrus=ld.findByNgayRoiDi(dateNayroidi);
            
            if(quanlytamtrus!=null){
                DefaultTableModel model= (DefaultTableModel)tbquanlytamtru.getModel();// muốn dùng table thì pải có hàm này 
        model.setRowCount(0);//clear thable
            for(quanlytamtru o : quanlytamtrus){
            model.addRow(new Object[]{o.getMaTamTru(),o.getHoTen(),o.getNTNS(),o.getGioiTinh(),o.getNoiOTamTru(),o.getNgayDangKy(),o.getNgayChuyenDen(),o.getNgayRoiDi(),o.getMaSoNhanKhau()});
            
        }
            }
            
        } catch (Exception e) {
            
        }
        }
        //
        if(txtNgaydangky!=null){
        try {
            SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");// muốn dùng dc date time thì pải có hai dòng này dòng 1
            String dateNaydangky = sdf.format(txtNgaydangky.getDate());// dòng 2.
            loadDAO ld = new loadDAO();
            List<quanlytamtru> quanlytamtrus=null;
            quanlytamtrus=ld.findByNgayDangKy(dateNaydangky);
            
            if(quanlytamtrus!=null){
                DefaultTableModel model= (DefaultTableModel)tbquanlytamtru.getModel();// muốn dùng table thì pải có hàm này 
        model.setRowCount(0);//clear thable
            for(quanlytamtru o : quanlytamtrus){
            model.addRow(new Object[]{o.getMaTamTru(),o.getHoTen(),o.getNTNS(),o.getGioiTinh(),o.getNoiOTamTru(),o.getNgayDangKy(),o.getNgayChuyenDen(),o.getNgayRoiDi(),o.getMaSoNhanKhau()});
            
        }
            }
            
        } catch (Exception e) {

        }
        }
        //
         //
        if(txtNTNS!=null){
        try {
            SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");// muốn dùng dc date time thì pải có hai dòng này dòng 1
            String dateNTNS = sdf.format(txtNTNS.getDate());// dòng 2.
            loadDAO ld = new loadDAO();
            List<quanlytamtru> quanlytamtrus=null;
            quanlytamtrus=ld.findByNTNS(dateNTNS);
            
            if(quanlytamtrus!=null){
                DefaultTableModel model= (DefaultTableModel)tbquanlytamtru.getModel();// muốn dùng table thì pải có hàm này 
        model.setRowCount(0);//clear thable
            for(quanlytamtru o : quanlytamtrus){
            model.addRow(new Object[]{o.getMaTamTru(),o.getHoTen(),o.getNTNS(),o.getGioiTinh(),o.getNoiOTamTru(),o.getNgayDangKy(),o.getNgayChuyenDen(),o.getNgayRoiDi(),o.getMaSoNhanKhau()});
            
        }
            }
            
        } catch (Exception e) {

        }
        }
        //
//         if(txtMatamtru.getText().equals("")){
//          try {
//            
//            loadDAO ld = new loadDAO();
//            quanlytamtru qltt=ld.findByid(txtGioitinh.getText());
//            
//            if(qltt!=null){
//                DefaultTableModel model= (DefaultTableModel)tbquanlytamtru.getModel();// muốn dùng table thì pải có hàm này 
//        model.setRowCount(0);//clear thable
//        model.addRow(new Object[]{qltt.getMaTamTru(),qltt.getHoTen(),qltt.getNTNS(),qltt.getGioiTinh(),qltt.getNoiOTamTru(),qltt.getNgayDangKy(),qltt.getNgayChuyenDen(),qltt.getNgayRoiDi(),qltt.getMaSoNhanKhau()});
//            }
//            
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "ERROR: "+e.getMessage());
//            e.printStackTrace();
//        }
//          }
//        if(txtGioitinh.getText().equals("")){
//        try {
//            
//            loadDAO ld = new loadDAO();
//            quanlytamtru qltt=ld.findByid(txtMatamtru.getText());
//            
//            if(qltt!=null){
//                DefaultTableModel model= (DefaultTableModel)tbquanlytamtru.getModel();// muốn dùng table thì pải có hàm này 
//        model.setRowCount(0);//clear thable
//        model.addRow(new Object[]{qltt.getMaTamTru(),qltt.getHoTen(),qltt.getNTNS(),qltt.getGioiTinh(),qltt.getNoiOTamTru(),qltt.getNgayDangKy(),qltt.getNgayChuyenDen(),qltt.getNgayRoiDi(),qltt.getMaSoNhanKhau()});
//            }
//            
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "ERROR: "+e.getMessage());
//            e.printStackTrace();
//        }
//        }

//        //tim theo gioi tinh tìm tất cả
//          try {
//            
//            loadDAO ld = new loadDAO();
//            List<quanlytamtru> quanlytamtrus=null;
//            quanlytamtrus=ld.findByGioiTinh(txtTIMKIEM.getText());
//            
//            if(quanlytamtrus!=null){
//                DefaultTableModel model= (DefaultTableModel)tbquanlytamtru.getModel();// muốn dùng table thì pải có hàm này 
//        model.setRowCount(0);//clear thable
//            for(quanlytamtru o : quanlytamtrus){
//            model.addRow(new Object[]{o.getMaTamTru(),o.getHoTen(),o.getNTNS(),o.getGioiTinh(),o.getNoiOTamTru(),o.getNgayDangKy(),o.getNgayChuyenDen(),o.getNgayRoiDi(),o.getMaSoNhanKhau()});
//            
//        }
//            }
//            
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "ERROR: "+e.getMessage());
//            e.printStackTrace();
//        }

           
    }//GEN-LAST:event_btnTIMKIEMActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        try {
            SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");// muốn dùng dc date time thì pải có hai dòng này dòng 1
            String dateNTNS = sdf.format(txtNTNS.getDate());// dòng 2.
            String dateNgaychuyenden=sdf.format(txtNgaychuyenden.getDate());
            String dateNgaydangky =sdf.format(txtNgaydangky.getDate());
            String dateNgayroidi =sdf.format(txtNgayroidi.getDate());
            quanlytamtru qltt = new quanlytamtru();
//            qltt.setSoSHK(Integer.parseInt(txtSoSHK.getText()));
//            qlshk.setNgaycap(date);
//            qlshk.setNoithuongtru(txtNoithuongtru.getText());
//            qlshk.setTenchuho(txtTenchuho.getText());
            qltt.setMaTamTru(txtMatamtru.getText());
            qltt.setGioiTinh(txtGioitinh.getText());
            qltt.setHoTen(txtHovaten.getText());
            qltt.setMaSoNhanKhau(txtMasonhankhau.getText());
            qltt.setNoiOTamTru(txtNoitamtru.getText());
            qltt.setNTNS(dateNTNS);
            qltt.setNgayChuyenDen(dateNgaychuyenden);
            qltt.setNgayDangKy(dateNgaydangky);
            qltt.setNgayRoiDi(dateNgayroidi);
            
//            String matamtruString=txtMatamtru.getText();
//            String hotenString=txtGioitinh.getText();
//            String gioitinhString=txtGioitinh.getText();
//            String masonhankhauString=txtMasonhankhau.getText();
//            String noiotamtruString=txtNoitamtru.getText();
//            Date ngay =txtNTNS.getDate();
            
            loadDAO ld1 =new loadDAO();
            if(ld1.update(qltt)){
                JOptionPane.showMessageDialog(this, "SỬA THÔNG TIN THÀNH CÔNG");
            }else{
                JOptionPane.showMessageDialog(this, "MA TẠM TRÚ KHÔNG ĐƯỢC SỮA\n SỬA THÔNG TIN KHÔNG THÀNH CÔNG");
            }
            ld1.update(qltt);
            
            List<quanlytamtru> list=ld1.getALLquanlytamtru();
        DefaultTableModel model= (DefaultTableModel)tbquanlytamtru.getModel();// muốn dùng table thì pải có hàm này 
        model.setRowCount(0);//clear thable
        for(quanlytamtru o : list){
            model.addRow(new Object[]{o.getMaTamTru(),o.getHoTen(),o.getNTNS(),o.getGioiTinh(),o.getNoiOTamTru(),o.getNgayDangKy(),o.getNgayChuyenDen(),o.getNgayRoiDi(),o.getMaSoNhanKhau()});
            
        }

            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR:" +e.getMessage());
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
                try {
//            SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyy");// muốn dùng dc date time thì pải có hai dòng này dòng 1
//            String dateNTNS = sdf.format(txtNTNS.getDate());// dòng 2.
//            String dateNgaychuyenden=sdf.format(txtNgaychuyenden.getDate());
//            String dateNgaydangky =sdf.format(txtNgaydangky.getDate());
//            String dateNgayroidi =sdf.format(txtNgayroidi.getDate());
//            quanlytamtru qltt = new quanlytamtru();
////            qltt.setSoSHK(Integer.parseInt(txtSoSHK.getText()));
////            qlshk.setNgaycap(date);
////            qlshk.setNoithuongtru(txtNoithuongtru.getText());
////            qlshk.setTenchuho(txtTenchuho.getText());
//            qltt.setMaTamTru(txtMatamtru.getText());
//            qltt.setGioiTinh(txtGioitinh.getText());
//            qltt.setHoTen(txtHovaten.getText());
//            qltt.setMaSoNhanKhau(txtMasonhankhau.getText());
//            qltt.setNoiOTamTru(txtNoitamtru.getText());
//            qltt.setNTNS(dateNTNS);
//            qltt.setNgayChuyenDen(dateNgaychuyenden);
//            qltt.setNgayDangKy(dateNgaydangky);
//            qltt.setNgayRoiDi(dateNgayroidi);
            
//            String matamtruString=txtMatamtru.getText();
//            String hotenString=txtGioitinh.getText();
//            String gioitinhString=txtGioitinh.getText();
//            String masonhankhauString=txtMasonhankhau.getText();
//            String noiotamtruString=txtNoitamtru.getText();
//            Date ngay =txtNTNS.getDate();
            
            loadDAO ld1 =new loadDAO();
            if(ld1.Delete(txtMatamtru.getText())){
                JOptionPane.showMessageDialog(this, "XÓA THÀNH CÔNG THÔNG TIN");
            }else{
                JOptionPane.showMessageDialog(this, "XÓA KHÔNG THÀNH CÔNG");
            }
            ld1.Delete(txtMatamtru.getText());
            
            List<quanlytamtru> list=ld1.getALLquanlytamtru();
        DefaultTableModel model= (DefaultTableModel)tbquanlytamtru.getModel();// muốn dùng table thì pải có hàm này 
        model.setRowCount(0);//clear thable
        for(quanlytamtru o : list){
            model.addRow(new Object[]{o.getMaTamTru(),o.getHoTen(),o.getNTNS(),o.getGioiTinh(),o.getNoiOTamTru(),o.getNgayDangKy(),o.getNgayChuyenDen(),o.getNgayRoiDi(),o.getMaSoNhanKhau()});
            
        }

            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR:" +e.getMessage());
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jComboBoxnamnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxnamnuActionPerformed
        // TODO add your handling code here:
        
        String sletedvalue = jComboBoxnamnu.getSelectedItem().toString();
        
        txtGioitinh.setText(sletedvalue);
    }//GEN-LAST:event_jComboBoxnamnuActionPerformed

    private void txtMatamtruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatamtruActionPerformed
        // TODO add your handling code here:
        try {
            
            loadDAO ld = new loadDAO();
            quanlytamtru qltt=ld.findByid(txtMatamtru.getText());
            
            if(qltt!=null){
                DefaultTableModel model= (DefaultTableModel)tbquanlytamtru.getModel();// muốn dùng table thì pải có hàm này 
        model.setRowCount(0);//clear thable
        model.addRow(new Object[]{qltt.getMaTamTru(),qltt.getHoTen(),qltt.getNTNS(),qltt.getGioiTinh(),qltt.getNoiOTamTru(),qltt.getNgayDangKy(),qltt.getNgayChuyenDen(),qltt.getNgayRoiDi(),qltt.getMaSoNhanKhau()});
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: "+e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtMatamtruActionPerformed

    private void txtGioitinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGioitinhActionPerformed
        // TODO add your handling code here:
          try {
            
            loadDAO ld = new loadDAO();
            List<quanlytamtru> quanlytamtrus=null;
            quanlytamtrus=ld.findByGioiTinh(txtGioitinh.getText());
            
            if(quanlytamtrus!=null){
                DefaultTableModel model= (DefaultTableModel)tbquanlytamtru.getModel();// muốn dùng table thì pải có hàm này 
        model.setRowCount(0);//clear thable
            for(quanlytamtru o : quanlytamtrus){
            model.addRow(new Object[]{o.getMaTamTru(),o.getHoTen(),o.getNTNS(),o.getGioiTinh(),o.getNoiOTamTru(),o.getNgayDangKy(),o.getNgayChuyenDen(),o.getNgayRoiDi(),o.getMaSoNhanKhau()});
            
        }
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: "+e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtGioitinhActionPerformed

    private void txtNgaychuyendenAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtNgaychuyendenAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaychuyendenAncestorAdded

    private void txtHovatenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHovatenActionPerformed
        // TODO add your handling code here:
           try {
            
            loadDAO ld = new loadDAO();
            List<quanlytamtru> quanlytamtrus=null;
            quanlytamtrus=ld.findByHoTen(txtHovaten.getText());
            
            if(quanlytamtrus!=null){
                DefaultTableModel model= (DefaultTableModel)tbquanlytamtru.getModel();// muốn dùng table thì pải có hàm này 
        model.setRowCount(0);//clear thable
            for(quanlytamtru o : quanlytamtrus){
            model.addRow(new Object[]{o.getMaTamTru(),o.getHoTen(),o.getNTNS(),o.getGioiTinh(),o.getNoiOTamTru(),o.getNgayDangKy(),o.getNgayChuyenDen(),o.getNgayRoiDi(),o.getMaSoNhanKhau()});
            
        }
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: "+e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtHovatenActionPerformed

    private void txtNoitamtruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoitamtruActionPerformed
        // TODO add your handling code here:
           try {
            
            loadDAO ld = new loadDAO();
            List<quanlytamtru> quanlytamtrus=null;
            quanlytamtrus=ld.findByNoiOTamTru(txtNoitamtru.getText());
            
            if(quanlytamtrus!=null){
                DefaultTableModel model= (DefaultTableModel)tbquanlytamtru.getModel();// muốn dùng table thì pải có hàm này 
        model.setRowCount(0);//clear thable
            for(quanlytamtru o : quanlytamtrus){
            model.addRow(new Object[]{o.getMaTamTru(),o.getHoTen(),o.getNTNS(),o.getGioiTinh(),o.getNoiOTamTru(),o.getNgayDangKy(),o.getNgayChuyenDen(),o.getNgayRoiDi(),o.getMaSoNhanKhau()});
            
        }
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: "+e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtNoitamtruActionPerformed

    private void txtMasonhankhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMasonhankhauActionPerformed
        // TODO add your handling code here:
           try {
            
            loadDAO ld = new loadDAO();
            List<quanlytamtru> quanlytamtrus=null;
            quanlytamtrus=ld.findBymaSoNhanKhau(txtMasonhankhau.getText());
            
            if(quanlytamtrus!=null){
                DefaultTableModel model= (DefaultTableModel)tbquanlytamtru.getModel();// muốn dùng table thì pải có hàm này 
        model.setRowCount(0);//clear thable
            for(quanlytamtru o : quanlytamtrus){
            model.addRow(new Object[]{o.getMaTamTru(),o.getHoTen(),o.getNTNS(),o.getGioiTinh(),o.getNoiOTamTru(),o.getNgayDangKy(),o.getNgayChuyenDen(),o.getNgayRoiDi(),o.getMaSoNhanKhau()});
            
        }
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: "+e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtMasonhankhauActionPerformed

    private void txtotrongnhiunamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtotrongnhiunamActionPerformed
        // TODO add your handling code here:
    try {
            
            loadDAO ld = new loadDAO();
            List<quanlytamtru> quanlytamtrus=null;
            quanlytamtrus=ld.findByNam(txtotrongnhiunam.getText());
            
            if(quanlytamtrus!=null){
                DefaultTableModel model= (DefaultTableModel)tbquanlytamtru.getModel();// muốn dùng table thì pải có hàm này 
        model.setRowCount(0);//clear thable
            for(quanlytamtru o : quanlytamtrus){
            model.addRow(new Object[]{o.getMaTamTru(),o.getHoTen(),o.getNTNS(),o.getGioiTinh(),o.getNoiOTamTru(),o.getNgayDangKy(),o.getNgayChuyenDen(),o.getNgayRoiDi(),o.getMaSoNhanKhau()});
            
        }
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: "+e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtotrongnhiunamActionPerformed

    private void txtobaonhiuthangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtobaonhiuthangActionPerformed
        // TODO add your handling code here:
        
          try {
            
            loadDAO ld = new loadDAO();
            List<quanlytamtru> quanlytamtrus=null;
            quanlytamtrus=ld.findByThang(txtobaonhiuthang.getText());
            
            if(quanlytamtrus!=null){
                DefaultTableModel model= (DefaultTableModel)tbquanlytamtru.getModel();// muốn dùng table thì pải có hàm này 
        model.setRowCount(0);//clear thable
            for(quanlytamtru o : quanlytamtrus){
            model.addRow(new Object[]{o.getMaTamTru(),o.getHoTen(),o.getNTNS(),o.getGioiTinh(),o.getNoiOTamTru(),o.getNgayDangKy(),o.getNgayChuyenDen(),o.getNgayRoiDi(),o.getMaSoNhanKhau()});
            
        }
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: "+e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtobaonhiuthangActionPerformed

    private void txtotrongbaolauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtotrongbaolauActionPerformed
        // TODO add your handling code here:
         try {
            
            loadDAO ld = new loadDAO();
            List<quanlytamtru> quanlytamtrus=null;
            quanlytamtrus=ld.findByNgay(txtotrongbaolau.getText());
            
            if(quanlytamtrus!=null){
                DefaultTableModel model= (DefaultTableModel)tbquanlytamtru.getModel();// muốn dùng table thì pải có hàm này 
        model.setRowCount(0);//clear thable
            for(quanlytamtru o : quanlytamtrus){
            model.addRow(new Object[]{o.getMaTamTru(),o.getHoTen(),o.getNTNS(),o.getGioiTinh(),o.getNoiOTamTru(),o.getNgayDangKy(),o.getNgayChuyenDen(),o.getNgayRoiDi(),o.getMaSoNhanKhau()});
            
        }
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: "+e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtotrongbaolauActionPerformed

    private void btnThoatAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnThoatAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatAncestorAdded
     private void processLoginSuccessful(){
//    lbloginname.setText(ShareData.nguoiDangNhap.getTendangnhap());
//    lbrole.setText(ShareData.nguoiDangNhap.getVaitro());
    
    if(ShareData.nguoiDangNhap.getVaitro().equals("NhanVien")){
        btnNhapmoi.setEnabled(true);
        btnTIMKIEM.setEnabled(true);
        btnThem.setEnabled(true);
        btnXoa.setEnabled(true);
        btnSua.setEnabled(true);
        
    }else if(ShareData.nguoiDangNhap.getVaitro().equals("NguoiDan")){
//        jScrollPane1.setAutoscrolls(false);
//        jScrollPane1.setDoubleBuffered(false);
//        jScrollPane1.setFocusCycleRoot(false);
//        jScrollPane1.setFocusable(false);
        
//        jScrollPane1.setWheelScrollingEnabled(false);
//           jScrollPane1.repaint(40, 40, 300, 200);
//          jScrollPane1.setSize(300, 200);
////          jScrollPane1.setLocation(0, 100);
//        tbquanlytamtru.setSize(300, 200);
             jScrollPane1.repaint();
        
        
        
        btnNhapmoi.setVisible(false);
//        btnTIMKIEM.setVisible(false);
//        btnThem.setVisible(false);
//        btnXoa.setVisible(false);
//        btnSua.setVisible(false);
//        txtotrongnhiunam.setVisible(false);
//        jLabel14.setVisible(false);
//                jLabel16.setVisible(false);
//                        jLabel15.setVisible(false);
//                        jLabel17.setVisible(false);
//                                txtobaonhiuthang.setVisible(false);
//                                jLabel12.setVisible(false);
//                                        txtotrongbaolau.setVisible(false);
//                                        jLabel13.setVisible(false);
//                                       
//                                        
//                                        
//                                            private javax.swing.JButton btnNhapmoi;
    btnSua.setVisible(false);
    btnTIMKIEM.setVisible(false);
    btnThem.setVisible(false);
    btnXoa.setVisible(false);
    jComboBoxnamnu.setVisible(false);
    jLabel11.setVisible(false);
    jLabel10.setVisible(false);

    jLabel12.setVisible(false);
    jLabel13.setVisible(false);
    jLabel14.setVisible(false);
    jLabel15.setVisible(false);
    jLabel16.setVisible(false);
    jLabel17.setVisible(false);
    jLabel2.setVisible(false);
    jLabel3.setVisible(false);
    jLabel4.setVisible(false);
    jLabel5.setVisible(false);
    jLabel6.setVisible(false);
    jPanel3.setVisible(false);
    jLabel1.setVisible(false);
    jLabel7.setVisible(false);
    jLabel9.setVisible(false);
    jLabel7.setVisible(false);
    jLabel8.setVisible(false);
    jLabel9.setVisible(false);

    jPanel3.setVisible(false);

    jTextField8.setVisible(false);

    txtGioitinh.setVisible(false);
    txtHovaten.setVisible(false);
    txtMasonhankhau.setVisible(false);
    txtMatamtru.setVisible(false);
    txtNTNS.setVisible(false);
    txtNgaychuyenden.setVisible(false);
    txtNgaydangky.setVisible(false);
    txtNgayroidi.setVisible(false);
    txtNoitamtru.setVisible(false);
    txtobaonhiuthang.setVisible(false);
    txtotrongbaolau.setVisible(false);
    txtotrongnhiunam.setVisible(false);
//    
//    jLabel11.setVisible(false);
//btnThoat.setVisible(false);

   
////        jPanel1.setSize(864,554);
//        jPanel1.setBounds(0,0,864,554);
//        jLabel11.setBounds(10, 10,33, 320);

    }
        
    
    }
    /**the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORMQUANLYTAMTRU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORMQUANLYTAMTRU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORMQUANLYTAMTRU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORMQUANLYTAMTRU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORMQUANLYTAMTRU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNhapmoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTIMKIEM;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> jComboBoxnamnu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTable tbquanlytamtru;
    private javax.swing.JTextField txtGioitinh;
    private javax.swing.JTextField txtHovaten;
    private javax.swing.JTextField txtMasonhankhau;
    private javax.swing.JTextField txtMatamtru;
    private com.toedter.calendar.JDateChooser txtNTNS;
    private com.toedter.calendar.JDateChooser txtNgaychuyenden;
    private com.toedter.calendar.JDateChooser txtNgaydangky;
    private com.toedter.calendar.JDateChooser txtNgayroidi;
    private javax.swing.JTextField txtNoitamtru;
    private javax.swing.JTextField txtobaonhiuthang;
    private javax.swing.JTextField txtotrongbaolau;
    private javax.swing.JTextField txtotrongnhiunam;
    // End of variables declaration//GEN-END:variables
}
